name: Alpine Image Builder - Latest
on:
  push:
    branches: [ master, develop ]

jobs:
  prepare:
    name: "Prepare Environment"
    runs-on: ubuntu-latest

    steps:
    - name: Check out from head
      id: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create temporary directories
      id: create_directories
      run: |
        mkdir ${GITHUB_WORKSPACE}/artifact
        mkdir ${GITHUB_WORKSPACE}/image
    - name: Create release Docker
      id: docker_build
      run: |
        docker build docker --file docker/Dockerfile \
        --pull --tag imager
  build:
    name: "Build images"
    needs: prepare
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    releases: [ "3.11.6", "3.12.0" ]
    #    arch: [ aarch64, armhf, armv7 ]
    steps:
    - name: Check out from head
      id: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create storage directories
      id: mkdir
      run: |
        mkdir ${GITHUB_WORKSPACE}/artifact
        mkdir ${GITHUB_WORKSPACE}/image
    - name: Build ${{ matrix.release }} ${{ matrix.arch }}
      id: build
      run: |
        ${GITHUB_WORKSPACE}/build_images.sh ${GITHUB_WORKSPACE}/conf/release.conf
    - name: Release latest
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: latest
        tag_name: latest
        fail_on_unmatched_files: true
        files: |
          artifact/*img.gz
          artifact/alpine-rpi-aarch64-3.11.6.img.gz
          artifact/alpine-rpi-aarch64-3.12.0.img.gz

# vim:ft=yaml:sw=2:ts=2:et
