## Main workflow for building the images
name: Alpine Image Builder
on:
  push:
    branches:
      - master
      - release/*
  repository_dispatch:
    types: [ buildimages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out ${{ github.ref }}
      id: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create temporary directories
      id: mkdir
      run: |
        mkdir ${GITHUB_WORKSPACE}/image
        mkdir ${GITHUB_WORKSPACE}/artifact
    - name: Build images
      id: image_build
      run: |
        ${GITHUB_WORKSPACE}/build_images.sh ${GITHUB_WORKSPACE}/conf/release.conf
    - name: Upload log artifacts
      id: artifact_logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ${GITHUB_WORKSPACE}/**/*log
    - name: Upload image artifacts
      id: artifact_images
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: ${GITHUB_WORKSPACE}/**/*bz2

# vim:ft=yaml:sw=2:ts=2:et
