name: Build for Raspberry Pi Imager
on:
  push:
    branches: [ master ]

jobs:
  rpi_image_release:
    permissions:
      contents: write
    name: "Build images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #release: [ "3.16.6", "3.17.4", "3.18.2" ]
        #platform: [ rpi, rpi4, aarch64 ]
        release: [ "3.17.4", "3.18.2" ]
        platform: [ rpi, rpi4 ]
    steps:
      - name: Check out from head
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create storage directories
        id: mkdir
        run: |
          mkdir ${GITHUB_WORKSPACE}/artifact
          mkdir ${GITHUB_WORKSPACE}/image

      - name: Setup qemu environment
        uses: docker/setup-qemu-action@v2
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.release }} ${{ matrix.platform }}
        id: build
        run: |
          ${GITHUB_WORKSPACE}/imager_release.sh ${{ matrix.release }} ${{ matrix.platform }}
      - name: Compress image
        id: compress
        run: |
          gzip -k ${GITHUB_WORKSPACE}/image/alpine-${{ matrix.release }}-${{ matrix.platform }}.img
      ## Create a release with the number from matrix.releases 
      ## and the tag from matrix.arch
      #- name: Create release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ matrix.release }}-${{ matrix.platform }}
      #    release_name: ${{ matrix.release }}-${{ matrix.platform }}
      #    body: Automatic release - ${{ github.sha }}
      #    draft: true
      #    prerelease: false
      ## DEBUGGING
      - name: debug - list files
        run: |
          ls -la ${GITHUB_WORKSPACE}/artifact
          ls -la ${GITHUB_WORKSPACE}/image
      ## Upload the artifacts to the release
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: alpine-${{ matrix.release }}-${{ matrix.platform }}
          tag_name: ${{ matrix.release }}-${{ matrix.platform }}
          fail_on_unmatched_files: true
          body: Automatic release - ${{ matrix.release }} - ${{ github.sha }}
          ## XXX: set to draft
          draft: true
          files: |
            image/alpine-${{ matrix.release }}-${{matrix.platform }}.img
            image/alpine-${{ matrix.release }}-${{matrix.platform }}.img.gz
            image/alpine-${{ matrix.release }}-${{matrix.platform }}.log