name: Build for Raspberry Pi Imager
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: "Build images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #release: [ "3.16.6", "3.17.4", "3.18.2" ]
        #platform: [ rpi, rpi4, aarch64 ]
        release: [ "3.17.4", "3.18.2" ]
        platform: [ rpi, rpi4 ]
    steps:
      - name: Check out from head
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create storage directories
        id: mkdir
        run: |
          mkdir ${GITHUB_WORKSPACE}/artifact
          mkdir ${GITHUB_WORKSPACE}/image

      - name: Setup qemu environment
        uses: docker/setup-qemu-action@v2
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.release }} ${{ matrix.platform }}
        id: build
        run: |
          ${GITHUB_WORKSPACE}/imager_release.sh ${{ matrix.release }} ${{ matrix.platform }}
      - name: Compress resulting image
        id: compress
        run: |
          gzip ${GITHUB_WORKSPACE}/image/alpine-${{ matrix.release }}-${{ matrix.platform }}.img
      ## Create a release with the number from matrix.releases 
      ## and the tag from matrix.arch
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.release }}-${{ matrix.platform }}
          release_name: ${{ matrix.release }}-${{ matrix.platform }}
          body: Automatic release - ${{ github.sha }}
          draft: true
          prerelease: false
      ## Upload the artifacts to the release
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/image
          asset_name: ${{ matrix.release }}-${{ matrix.platform }}.img.gz
          asset_content_type: application/gzip