name: Test Runner
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the test script
      run: ${GITHUB_WORKSPACE}/script/workflow_test.sh
